version: "3.1"

volumes:
  mongo:

services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: users
